def alias(tower):
    upgrades = ["Ultra-Juggernaut", "Plasma Monkey Fan Club", "Crossbow Master", "Glaive Lord", "Perma Charge", "MOAB Domination", "Bloon Crush", "MOAB Eliminator", "Bomb Blitz", "Inferno Ring", "Super Maelstrom", "The Tack Zone", "Super Brittle", "Absolute Zero", "Icicle Impale", "The Bloon Solver", "Glue Storm", "Super Glue", "Cripple MOAB", "Elite Sniper", "Elite Defender", "Energizer", "Pre-Emptive Strike", "Sub Commander", "Carrier Flagship", "Pirate Lord", "Trade Empire", "Sky Shredder", "Tsar Bomba", "Flying Fortress", "Apache Prime", "Special Poperations", "Comanche Commander", "The Biggest One", "Pop and Awe", "Blooncineration", "Ray of Doom", "M.A.D.", "Bloon Exclusion Zone", "Archmage", "Wizard Lord Phoenix", "Prince of Darkness", "True Sun God", "The Anti-Bloon", "Legend of the Night", "Grandmaster Ninja", "grand Saboteur", "Master Bomber", "Permanent Brew", "Total Transformation", "Bloon Master Alchemist", "Superstorm", "Spirit of the Forest", "Avatar of Wrath", "Banana Central", "Monkey-Nomics", "Monkey Wall Street", "Super Mines", "Carpet of Spikes", "Perma-Spike", "Primary Expertise", "Homeland Defense", "Monkeyopolis", "Sentry Paragon", "UltraBoost", "XXXL Trap", "Quincy", "Gwendolin", "Striker Jones", "Obyn Greenfoot", "Captain Churchill", "Benjamin", "Ezili", "Pat Fusty", "Adora", "Admiral Brickell", "Etienne", "Sauda", "Psi", "Geraldo"]
    upgradeAliases = ['ultra-juggernaut', 'ujug', 'juggernaut', 'plasma monkey fan club', 'pmfc', 'crossbow master', 'glaive lord', 'perma charge', 'moab domination', 'bloon crush', 'moab eliminator', 'bomb blitz', 'inferno ring', 'super maelstrom', 'the tack zone', 'super brittle', 'absolute zero', 'icicle impale', 'the bloon solver', 'glue storm', 'super glue', 'cripple moab', 'elite sniper', 'elite defender', 'energizer', 'pre-emptive strike', 'sub commander', 'carrier flagship', 'pirate lord', 'trade empire', 'sky shredder', 'tsar bomba', 'flying fortress', 'apache prime', 'special poperations', 'comanche commander', 'the biggest one', 'pop and awe', 'blooncineration', 'ray of doom', 'm.a.d.', 'bloon exclusion zone', 'archmage', 'wizard lord phoenix', 'prince of darkness', 'true sun god', 'the anti-bloon', 'legend of the night', 'grandmaster ninja', 'grand saboteur', 'master bomber', 'permanent brew', 'total transformation', 'bloon master alchemist', 'superstorm', 'spirit of the forest', 'avatar of wrath', 'banana central', 'monkey-nomics', 'monkey wall street', 'super mines', 'carpet of spikes', 'perma-spike', 'primary expertise', 'homeland defense', 'monkeyopolis', 'sentry paragon', 'ultraboost', 'xxxl trap', 'quincy', 'gwendolin', 'striker jones', 'obyn greenfoot', 'captain churchill', 'benjamin', 'ezili', 'pat fusty', 'adora', 'admiral brickell', 'etienne', 'sauda', 'psi', 'geraldo']
    lowerCaseUpgrades = ['ultra-juggernaut', 'plasma monkey fan club', 'crossbow master', 'glaive lord', 'perma charge', 'moab domination', 'bloon crush', 'moab eliminator', 'bomb blitz', 'inferno ring', 'super maelstrom', 'the tack zone', 'super brittle', 'absolute zero', 'icicle impale', 'the bloon solver', 'glue storm', 'super glue', 'cripple moab', 'elite sniper', 'elite defender', 'energizer', 'pre-emptive strike', 'sub commander', 'carrier flagship', 'pirate lord', 'trade empire', 'sky shredder', 'tsar bomba', 'flying fortress', 'apache prime', 'special poperations', 'comanche commander', 'the biggest one', 'pop and awe', 'blooncineration', 'ray of doom', 'm.a.d.', 'bloon exclusion zone', 'archmage', 'wizard lord phoenix', 'prince of darkness', 'true sun god', 'the anti-bloon', 'legend of the night', 'grandmaster ninja', 'grand saboteur', 'master bomber', 'permanent brew', 'total transformation', 'bloon master alchemist', 'superstorm', 'spirit of the forest', 'avatar of wrath', 'banana central', 'monkey-nomics', 'monkey wall street', 'super mines', 'carpet of spikes', 'perma-spike', 'primary expertise', 'homeland defense', 'monkeyopolis', 'sentry paragon', 'ultraboost', 'xxxl trap', 'quincy', 'gwendolin', 'striker jones', 'obyn greenfoot', 'captain churchill', 'benjamin', 'ezili', 'pat fusty', 'adora', 'admiral brickell', 'etienne', 'sauda', 'psi', 'geraldo']
    
    if tower.lower() not in upgradeAliases:
        return "Tower doesn't exist"
    index = upgradeAliases.index(tower.lower())
    for i in range(len(upgradeAliases)):
        for j in range(len(upgrades)):
            if upgradeAliases[index-i] == lowerCaseUpgrades[j]:
                return upgrades[j]